export const API_KEY_HEADER_NAME = "X-API-KEY"
export const POPULATION_STATISTICS_START_YEAR = 1960
export const POPULATION_STATISTICS_END_YEAR = 2045
export const POPULATION_STATISTICS_STEP_YEAR = 5
